//! Keeps `README.md` honest about the CLI surface.
//!
//! README drift is this repo's recurring documentation failure: commands land,
//! the README stays put, and the gap is only noticed when someone reads both.
//! This test closes that loop mechanically — it asks the freshly built `rf`
//! binary what its surface actually is (`--help`, then `<sub> --help`) and
//! asserts the README documents all of it.
//!
//! It deliberately lives as a `cargo test` rather than a bespoke CI job:
//! `cargo test --locked` is already a step in `.github/workflows/ci.yml` *and* a
//! configured gate in both `roll_to_rolling_gates` and `rolling_to_main_gates`
//! in `.roll-flow.toml`. Being a test therefore makes documentation a PR check
//! and an `rf verify`/`graduate`/`promote` gate with no extra wiring.

mod harness;

use harness::Sandbox;

/// Subcommands that exist but are not ours to document.
///
/// `help` is generated by clap for every binary and documenting it would say
/// nothing about roll-flow.
const SKIP_SUBCOMMANDS: &[&str] = &["help"];

/// Flags clap attaches to everything, whose behaviour is universal and not
/// worth restating per subcommand in the README.
const SKIP_FLAGS: &[&str] = &["--help", "--version"];

/// The body of one clap help section (`Commands:`, `Options:`, ...).
///
/// Sections end at the next header, which is the next non-blank line starting
/// at column 0. Blank lines cannot be the terminator: when a flag has no doc
/// comment clap still emits its description line, as whitespace only, in the
/// middle of the section.
fn section<'a>(help: &'a str, header: &str) -> Vec<&'a str> {
    help.lines()
        .skip_while(|l| l.trim() != header)
        .skip(1)
        .take_while(|l| l.trim().is_empty() || l.starts_with(char::is_whitespace))
        .collect()
}

/// Pull the subcommand names out of the `Commands:` section of `rf --help`.
fn subcommands(help: &str) -> Vec<String> {
    section(help, "Commands:")
        .into_iter()
        .filter_map(|l| l.split_whitespace().next())
        .filter(|name| !SKIP_SUBCOMMANDS.contains(name))
        .map(String::from)
        .collect()
}

/// Pull the long flags out of the `Options:` section of `rf <sub> --help`.
///
/// Only the flag-spec portion of each line is parsed — the part before the
/// two-space gutter that separates it from the description. Descriptions
/// routinely mention other flags (`--land`, `--no-ff`, `--reason`), and
/// scanning the whole line would pick those up as if they belonged here.
fn long_flags(help: &str) -> Vec<String> {
    section(help, "Options:")
        .into_iter()
        .filter(|l| l.trim_start().starts_with('-'))
        .flat_map(|l| {
            let spec = l.trim().split("  ").next().unwrap_or("");
            spec.split(',')
                .map(|tok| tok.split_whitespace().next().unwrap_or("").to_string())
                .filter(|tok| tok.starts_with("--"))
                .collect::<Vec<_>>()
        })
        .filter(|flag| !SKIP_FLAGS.contains(&flag.as_str()))
        .collect()
}

/// The fenced block under `## Commands` in the README — the synopsis listing
/// one `rf <sub> [flags]` line per subcommand.
fn commands_block(readme: &str) -> String {
    readme
        .lines()
        .skip_while(|l| l.trim() != "## Commands")
        .skip_while(|l| !l.trim_start().starts_with("```"))
        .skip(1)
        .take_while(|l| !l.trim_start().starts_with("```"))
        .collect::<Vec<_>>()
        .join("\n")
}

#[test]
fn readme_documents_every_subcommand_and_flag() {
    let readme = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/README.md"))
        .expect("read README.md");
    let block = commands_block(&readme);
    assert!(
        !block.is_empty(),
        "could not find a fenced code block under `## Commands` in README.md"
    );

    // One sandbox, reused: `--help` needs no repo state, but the harness runner
    // is the established way to invoke the built binary.
    let sb = Sandbox::plain();
    let mut problems: Vec<String> = Vec::new();

    for sub in subcommands(&sb.rf(&["--help"]).combined()) {
        // The synopsis line for this subcommand, e.g. `rf prune [--dry-run] ...`.
        let synopsis = block
            .lines()
            .find(|l| l.trim_start().starts_with(&format!("rf {sub}")));

        let Some(synopsis) = synopsis else {
            problems.push(format!(
                "`rf {sub}` is missing from the `## Commands` block in README.md"
            ));
            continue;
        };

        if !readme.contains(&format!("### `{sub}`")) {
            problems.push(format!(
                "`rf {sub}` has no \"### `{sub}`\" section heading in README.md"
            ));
        }

        for flag in long_flags(&sb.rf(&[&sub, "--help"]).combined()) {
            if !synopsis.contains(&flag) {
                problems.push(format!(
                    "`rf {sub}` accepts `{flag}`, but the README synopsis omits it:\n      {}",
                    synopsis.trim()
                ));
            }
        }
    }

    assert!(
        problems.is_empty(),
        "README.md is out of sync with the CLI ({} problem(s)):\n  - {}\n\n\
         Update the `## Commands` block and the per-command `###` sections in \
         README.md to match `rf --help`.",
        problems.len(),
        problems.join("\n  - ")
    );
}
